# Setup
title: erjantj
url: https://erjantj.com
baseurl: ""
paginate: 10
paginate_path: blog/:num/
permalink: /blog/:year/:month/:day/:title:output_ext

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-HC77YBR67L

# Specify the author for blog posts
author: Yerzhan Torgayev

# Custom vars
version: 3.0.0

# Navbar page list
# nav:
#   - title: Blog
#     url: /archive

#   - title: About
#     url: /about

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: erjantj
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true
github_sort: updated
  
# Twitter
twitter_user: erjan_tj
twitter_tweet_button: true

# Linkedin
linkedin_user: yerzhan-torgayev

# Social Service Links
social_service_links: true